workflows:
  main:
    name: Build and Test
    environment:
      node: latest
      npm: latest
      react_native: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Run tests
        script: npm test
      - name: Build APK
        script: npm run android:build