workflows:
  main:
    name: Build and Test
    environment:
      node: latest
      npm: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: expo build:android