workflows:
  main:
    steps:
      - checkout: self
      - setup-android-sdk:
          components: build-tools-31.0.0, android-31
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - artifacts:
          - app/build/outputs/**/*.apk