workflows:
  main:
    name: Build APK
    environment:
      machine:
        type: mac-mini-2020
        image: latest
    scripts:
      - name: Install dependencies
        script: ./gradlew dependencies
      - name: Build APK
        script: ./gradlew assembleRelease