workflows:
  main:
    name: Build APK
    steps:
      - name: Download Flutter SDK
        script: |
          curl -O https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_2.10.3-stable.zip

      - name: Install dependencies
        script: |
          cd android
          ./gradlew dependencies

      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
