workflows:
  main:
    name: Build APK
    environment:
      flutter: latest
    scripts:
      - name: Install dependencies
        script: ./gradlew dependencies
      - name: Build APK
        script: ./gradlew assembleRelease