workflows:
  main:
    name: Build and Test
    environment:
      node: latest
      npm: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: npx react-native bundle --platform android --dev false --entry-file App.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res && cd android && ./gradlew clean && ./gradlew assembleRelease