name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.11.0'

    - name: Install dependencies
      run: npm install

    - name: Build Electron app
      run: npm run build

    - name: Set up Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Push artifacts to GitHub
      run: |
        git add .
        git commit -m "Add built artifacts"
        git push https://somkene12345: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@github.com/somkene12345/exposition.git HEAD:main
